server:
  port: 8090

jwt:
  secret: ${JWT_SECRET}

rabbitmq:
  schema: "amqp"
  host: "rabbitmq"
  port: 5672
  username: ${RABBITMQ_DEFAULT_USER}
  password: ${RABBITMQ_DEFAULT_PASS}
  queues:
    - name: "delete_queue"
      routingKey: "delete_user_rk"
      exchange: "delete_exchange"
      exchange_type: "direct"
      durable: true
      consumer: true
    # add more if needed
