version: '3.7'

services:
  doctori:
    build:
      context: ./services/doctori
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:8080"
    container_name: "doctori-app"
    networks:
      - mynetwork  # Attach the service to the custom network
    depends_on:
      - doctori-mysql
      - doctori-redis
    environment:
      DATABASE_HOST: doctori-mysql
      REDIS_PASSWORD: ${REDIS_DOCTORI_PASSWORD}
    volumes:
      - ./services/doctori:/workspace

  doctori-mysql:
    image: mysql:8.2.0
    build:
      context: ./services/doctori
      dockerfile: docker/mysql.Dockerfile
    container_name: "doctori-mysql"
    networks:
      - mynetwork  # Attach the service to the custom network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - doctori-mysql-data:/var/lib/mysql

  doctori-redis:
    image: redis:latest
    build:
        context: ./services/doctori
    container_name: "doctori-redis"
    networks:
      - mynetwork  # Attach the service to the custom network
    ports:
      - "6379:6379"
    volumes:
      - doctori-redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_DOCTORI_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_DOCTORI_PASSWORD}"]

volumes:
  doctori-mysql-data:
  doctori-redis-data:

networks:
  mynetwork:
