version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  rabbit_app:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8090:8090"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - rabbitmq
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-vf", "http://localhost:8090/api/rabbit/health-check"]
      interval: 20s
      timeout: 5s
      retries: 2

