version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  rabbit_app:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
