version: '3'
services:
  # MongoDB container
  mongodb:
    image: mongo:latest  # Use your MongoDB Docker image and tag
    container_name: mongodb
    build:
      context: .  # Use the context of your application's Dockerfile
      dockerfile: docker/mongo.Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_CONSULTATII_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CONSULTATII_PASSWORD}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  # Redis container
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_CONSULTATII_PASSWORD}

  # Your Go application container
  app_consultatii:
    build:
      context: .  # Use the context of your application's Dockerfile
      dockerfile: docker/api.Dockerfile
    container_name: app_consultatii
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      MONGO_CONSULTATII_DB: ${MONGO_CONSULTATII_DB}
    depends_on:
      - mongodb
      - redis
