version: '3.7'
services:
  # MongoDB container
  consultation_mongodb:
    image: mongo:latest  # Use your MongoDB Docker image and tag
    container_name: consultation_mongodb
    build:
      context: .  # Use the context of your application's Dockerfile
      dockerfile: docker/mongo.Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_CONSULTATII_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CONSULTATII_PASSWORD}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  # Redis container
  consultation_redis:
    image: redis:latest
    container_name: consultation_redis
    ports:
      - "6375:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_CONSULTATII_PASSWORD}

  # Your Go application container
  consultation_app:
    build:
      context: .  # Use the context of your application's Dockerfile
      dockerfile: docker/api.Dockerfile
    container_name: consultation_app
    ports:
      - "8085:8085"
    depends_on:
      - consultation_mongodb
      - consultation_redis
    env_file:
      - .env
    environment:
      MONGO_CONSULTATII_DB: ${MONGO_CONSULTATII_DB}
