server:
  port: 8080

mysql_db:
  host: mysql 
  port: 3306 
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  dbname: ${MYSQL_DATABASE}
  charset: utf8mb4 
  parseTime: true 
  maxOpenConns: 10 
  maxIdleConns: 3 
  connMaxLifetime: 3600

redis:
  host: redis
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0

jwt:
  secret: ${JWT_SECRET}