server:
  port: 8080

mysql_db:
  host: mysql 
  port: 3306 
  user: mihnea_pos
  password: mihnea_pos
  dbname: pos_db
  charset: utf8mb4 
  parseTime: true 
  maxOpenConns: 10 
  maxIdleConns: 3 
  connMaxLifetime: 3600

redis:
  host: redis
  port: 6379
  password: my_secure_password
  db: 0